# Generated by Django 3.2 on 2022-06-22 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saving', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='saving',
            name='number',
            field=models.IntegerField(default=1),
        ),
    ]
