# Generated by Django 3.2 on 2022-06-22 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saving', '0003_alter_saving_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saving',
            name='payback',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
