# Generated by Django 3.2 on 2022-06-22 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('saving', '0004_alter_saving_payback'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='saving',
            unique_together={('number', 'date')},
        ),
    ]
