# Generated by Django 3.2 on 2022-06-22 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('saving', '0005_alter_saving_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='saving',
            options={'ordering': ('number', 'date')},
        ),
    ]
