# Generated by Django 3.2 on 2022-06-23 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('saving', '0006_alter_saving_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Saving',
            new_name='SavingDetail',
        ),
    ]
