# Generated by Django 3.2 on 2022-06-23 00:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('saving', '0008_saving'),
    ]

    operations = [
        migrations.AddField(
            model_name='savingdetail',
            name='saving',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='saving.saving'),
            preserve_default=False,
        ),
    ]
