# Generated by Django 3.2 on 2022-06-23 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('saving', '0011_alter_savingdetail_saving'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savingdetail',
            name='saving',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saving_detail_set', to='saving.saving'),
        ),
    ]
