# Generated by Django 3.2 on 2022-08-16 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_alter_finance_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='finance',
            name='type',
            field=models.CharField(choices=[('PAY', 'Payment'), ('LOAN', 'Loan')], default='PAY', max_length=4),
        ),
    ]
