# Generated by Django 3.2 on 2022-08-23 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_remove_finance_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='finance',
            name='pay_date',
            field=models.DateField(null=True),
        ),
    ]
