# Generated by Django 3.2 on 2022-08-23 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_finance_pay_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finance',
            name='pay_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
