# Generated by Django 3.2 on 2022-08-30 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0010_alter_finance_time_frame'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finance',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
