# Generated by Django 3.2 on 2022-08-30 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0012_alter_finance_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finance',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
