# Generated by Django 3.2 on 2022-08-12 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('concept', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='concept',
            unique_together={('name', 'type')},
        ),
    ]
